In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)
df = pd.read_parquet('taxi_trip_engineering.parquet')
df

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Datetime,hour,day_of_week,Pickup Encoded,Drop Encoded,route_cluster,distance_per_hour,log_distance,distance_squared,distance_sqrt,is_peak_hour,is_weekend,is_night,hour_sin,hour_cos,day_sin,day_cos,traffic_score,route_avg_ctat_safe,rating_diff,avg_rating,low_driver_rating,low_customer_rating,driver_score,hourly_demand,route_demand,demand_pressure,route_count,log_price,log_ctat,log_route_count,log_route_price,log_route_ctat,time_distance_interaction,route_complexity,peak_pressure,route_ctat_mean,route_ctat_median,route_ctat_std,route_vtat_mean,route_vtat_median,hour_avg_ctat,hour_avg_vtat,hour_demand,dow_avg_ctat,dow_avg_vtat,distance_bin,dist_bin_ctat,dist_bin_vtat,log_distance_v2,rating_sum,rating_mult,rating_min,rating_max,rating_bucket,rating_bucket_ctat,rating_bucket_vtat,route_hour_key,route_hour_ctat,route_hour_vtat,minute,pickup_key,drop_key,estimated_pickup_time_minute,estimated_drop_time_minute,price_per_km,price_bucket,price_bucket_ctat,price_bucket_vtat
0,2024-01-01,00:19:34,"""CNR4352144""",Completed,"""CID8362794""",Motorcycle,Pasar Baru,Cilandak Timur,10.8,38.9,99000.0,37.98,4.8,4.8,Cash,No Cancellation,No Cancellation,No Cancellation,No Cancellation,0.0,No Cancellation,2024-01-01 00:19:34,0,0,110,18,4,4.312727,3.663049,1442.4804,6.162792,0,0,1,0.000000,1.000000,0.0,1.0,1,29.026393,0.00,4.625,0,0,4.8,1373,5,228.833333,5,11.502885,3.686376,1.791759,12.700787,3.394508,37.98,5,0,30.820000,31.20,9.496684,9.620000,10.80,29.024763,8.400510,1373,28.940847,8.432545,3,30.060481,8.487883,7.010743,9.6,23.04,4.8,4.8,4,29.983461,8.483689,110_18_0,38.9,10.8,19,110_0_19,18_0_19,18.90,11.55,2599.789916,0,29.126926,8.283577
1,2024-01-01,01:35:18,"""CNR9147645""",Completed,"""CID8300238""",Car,Kali Anyar,Rawamangun,8.5,15.1,114000.0,39.29,4.2,4.1,Uber Wallet,Cancelled,Changed Mind,Cancelled,Traffic Issue,0.0,Ride Cancelled Midway,2024-01-01 01:35:18,1,0,47,147,3,4.312727,3.696103,1543.7041,6.268174,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,0.10,4.150,0,1,0.0,1360,2,453.333333,2,11.643962,2.778819,1.098612,12.700787,3.394508,39.29,2,0,18.300000,18.30,4.525483,7.000000,7.00,28.935515,8.381618,1360,28.940847,8.432545,3,30.060481,8.487883,7.105852,8.3,17.22,4.1,4.2,3,28.674842,8.418815,47_147_1,15.1,8.5,35,47_1_35,147_1_35,27.00,3.40,2894.135567,1,29.069894,8.250120
2,2024-01-01,01:37:50,"""CNR1009222""",Cancelled by Driver,"""CID2030746""",Go Sedan,Serdang,Pengadegan,7.4,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Driver Taking Too Long,No Cancellation,No Reason Provided,1.0,Ride Cancelled Midway,2024-01-01 01:37:50,1,0,147,125,1,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.20,4.400,0,0,4.3,1360,4,272.000000,4,12.933624,3.394508,1.609438,12.700787,3.394508,23.72,4,0,28.750000,28.80,0.100000,10.900000,9.20,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,147_125_1,28.8,7.4,37,147_1_37,125_1_37,20.10,8.60,17380.352645,2,28.865348,8.671032
3,2024-01-01,01:48:03,"""CNR2740479""",Cancelled by Driver,"""CID3231181""",Auto,Tanah Tinggi,Kampung Rawa,5.6,28.8,414000.0,23.72,4.3,4.5,Debit Card,No Cancellation,Booked by Mistake,No Cancellation,No Reason Provided,1.0,Route Problem,2024-01-01 01:48:03,1,0,160,61,2,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.20,4.400,0,0,4.3,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,25.914286,25.90,3.223057,6.571429,5.60,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,160_61_1,28.8,5.6,48,160_1_48,61_1_48,28.40,5.80,17380.352645,2,28.865348,8.671032
4,2024-01-01,01:49:56,"""CNR7650148""",Cancelled by Driver,"""CID3381661""",Go Sedan,Jati,Batu Ceper,6.2,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Booked by Mistake,Cancelled,Vehicle Breakdown,1.0,Ride Cancelled Midway,2024-01-01 01:49:56,1,0,40,2,0,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.20,4.400,0,0,0.0,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,23.542857,20.60,6.484303,5.514286,6.20,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,40_2_1,28.8,6.2,49,40_1_49,2_1_49,31.57,6.60,17380.352645,2,28.865348,8.671032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,2024-12-30,22:58:00,"""CNR9030698""",Completed,"""CID6939658""",Motorcycle,Setu,Kembangan Utara,6.9,35.8,440000.0,12.85,4.4,4.8,UPI,No Cancellation,Changed Mind,Cancelled,Traffic Issue,0.0,App Error,2024-12-30 22:58:00,22,0,148,84,2,0.558696,2.628285,165.1225,3.584690,0,0,1,-0.500000,0.866025,0.0,1.0,1,25.260000,-0.40,4.600,0,0,0.0,5441,6,777.285714,6,12.994532,3.605498,1.945910,12.742693,3.268047,12.85,6,0,27.016667,26.15,6.237120,8.683333,7.95,29.112571,8.432659,5441,28.940847,8.432545,1,28.152500,8.043096,4.260973,9.2,21.12,4.4,4.8,4,29.983461,8.483689,148_84_22,35.8,6.9,58,148_22_58,84_22_58,28.80,7.55,33976.833977,3,29.283535,8.333253
149996,2024-12-30,23:03:14,"""CNR1507833""",Completed,"""CID9905090""",eBike,Jatinegara,Grogol Selatan,7.9,33.6,279000.0,39.36,3.8,4.3,UPI,No Cancellation,Driver Taking Too Long,Cancelled,Traffic Issue,1.0,App Error,2024-12-30 23:03:14,23,0,41,43,0,1.640000,3.697839,1549.2096,6.273755,0,0,1,-0.258819,0.965926,0.0,1.0,1,25.633333,-0.50,4.050,1,0,0.0,2762,4,552.400000,4,12.538971,3.543854,1.609438,12.331425,3.282164,39.36,4,0,27.625000,27.30,10.463389,7.750000,8.60,28.868356,8.447502,2762,28.940847,8.432545,3,30.060481,8.487883,7.110858,8.1,16.34,3.8,4.3,3,28.674842,8.418815,41_43_23,33.6,7.9,3,41_23_3,43_23_3,15.20,6.30,7070.451090,1,29.069894,8.250120
149997,2024-12-30,23:17:05,"""CNR2265113""",Completed,"""CID4170406""",Car,Kebon Melati,Galur,9.9,39.9,1855.0,38.91,4.3,4.6,UPI,Cancelled,Changed Mind,Cancelled,Wrong Location,0.0,Route Problem,2024-12-30 23:17:05,23,0,69,36,4,1.621250,3.686627,1513.9881,6.237788,0,0,1,-0.258819,0.965926,0.0,1.0,1,27.000000,-0.30,4.450,0,0,0.0,2762,5,460.333333,5,7.526179,3.711130,1.791759,13.003582,3.332205,38.91,5,0,29.580000,28.80,8.277802,8.020000,9.90,28.868356,8.447502,2762,28.940847,8.432545,3,30.060481,8.487883,7.078542,8.9,19.78,4.3,4.6,3,28.674842,8.418815,69_36_23,39.9,9.9,17,69_23_17,36_23_17,41.10,4.70,47.551910,0,29.126926,8.283577
149998,2024-12-30,23:21:12,"""CNR4066733""",Completed,"""CID8938559""",Uber XL,Utan Panjang,Pinang Ranti,2.6,26.7,520000.0,36.37,5.0,4.3,Uber Wallet,No Cancellation,Wrong Pickup Location,Cancelled,Traffic Issue,1.0,Ride Cancelled Midway,2024-12-30 23:21:12,23,0,174,132,1,1.515417,3.620868,1322.7769,6.030755,0,0,1,-0.258819,0.965926,0.0,1.0,1,25.833333,0.45,4.625,0,0,0.0,2762,4,552.400000,4,13.161586,3.321432,1.609438,12.861867,3.289645,36.37,4,0,26.050000,26.30,2.487971,6.675000,6.65,28.868356,8.447502,2762,28.940847,8.432545,3,30.060481,8.487883,6.889998,9.3,21.50,4.3,5.0,4,29.983461,8.483689,174_132_23,26.7,2.6,21,174_23_21,132_23_21,27.30,9.20,14258.294489,3,29.283535,8.333253
149999,2024-12-30,23:36:11,"""CNR6915581""",Incomplete,"""CID5185745""",Auto,Mampang Prapatan,Tegal Parang,3.5,11.9,571000.0,2.67,4.3,4.5,UPI,No Cancellation,Found Alternative,No Cancellation,No Reason Provided,0.0,Vehicle Breakdown,2024-12-30 23:36:11,23,0,94,168,1,0.111250,1.300192,7.1289,1.634013,0,0,1,-0.258819,0.965926,0.0,1.0,1,29.666667,-0.20,4.400,0,0,4.3,2762,10,251.090909,10,13.255146,2.557227,2.397895,12.865608,3.423176,2.67,10,0,27.890000,28.80,6.833813,8.140000,8.35,28.868356,8.447502,2762,28.940847,8.432545,0,27.916399,7.952362,1.482556,8.8,19.35,4.3,4.5,3,28.674842,8.418815,94_168_23,11.9,3.5,36,94_23_36,168_23_36,31.05,17.10,206137.184116,3,29.283535,8.333253

In [10]:
df['Vehicle Type'].value_counts()

Vehicle Type
Auto             37419
Car              29806
Go Sedan         27141
Motorcycle       22517
Premier Sedan    18111
eBike            10557
Uber XL           4449
Name: count, dtype: int64

In [15]:
df['day_sin'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 150000 entries, 0 to 149999
Series name: day_sin
Non-Null Count   Dtype
--------------   -----
150000 non-null  float64
dtypes: float64(1)
memory usage: 1.1 MB

In [6]:
df['day_cos'].sample(30)

86096    -0.222521
21282    -0.222521
88005    -0.900969
138381    1.000000
148818   -0.222521
63010     0.623490
18829    -0.900969
110094    0.623490
32922    -0.222521
98197     1.000000
30811    -0.900969
143657    0.623490
103695    0.623490
35854    -0.222521
129843    1.000000
142323   -0.900969
96566    -0.900969
142302   -0.900969
102029   -0.222521
115464    1.000000
27066    -0.222521
89857     1.000000
19829    -0.222521
129360    0.623490
114001   -0.900969
13093    -0.900969
116658   -0.900969
61562    -0.222521
121020    1.000000
140877    0.623490
Name: day_cos, dtype: float64

In [7]:
df['estimated_pickup_time_minute']

0         18.90
1         27.00
2         20.10
3         28.40
4         31.57
          ...
149995    28.80
149996    15.20
149997    41.10
149998    27.30
149999    31.05
Name: estimated_pickup_time_minute, Length: 150000, dtype: float64

In [5]:
df['Booking Status']

0                   Completed
1                   Completed
2         Cancelled by Driver
3         Cancelled by Driver
4         Cancelled by Driver
                 ...
149995              Completed
149996              Completed
149997              Completed
149998              Completed
149999             Incomplete
Name: Booking Status, Length: 150000, dtype: object

In [47]:
df['Vehicle Type'].value_counts()

Vehicle Type
Auto             37419
Car              29806
Go Sedan         27141
Motorcycle       22517
Premier Sedan    18111
eBike            10557
Uber XL           4449
Name: count, dtype: int64

In [48]:
df.columns.tolist()

['id',
 'Date',
 'Time',
 'user_id',
 'Booking Status',
 'Customer ID',
 'Vehicle Type',
 'Pickup Location',
 'Drop Location',
 'Avg VTAT',
 'Avg CTAT',
 'Booking Value',
 'Ride Distance',
 'Driver Ratings',
 'Customer Rating',
 'Payment Method',
 'Cancelled Rides by Customer',
 'Reason for cancelling by Customer',
 'Cancelled Rides by Driver',
 'Driver Cancellation Reason',
 'Incomplete Rides',
 'Incomplete Rides Reason',
 'Datetime',
 'hour',
 'day_of_week',
 'Pickup Encoded',
 'Drop Encoded',
 'route_cluster',
 'distance_per_hour',
 'log_distance',
 'distance_squared',
 'distance_sqrt',
 'is_peak_hour',
 'is_weekend',
 'is_night',
 'hour_sin',
 'hour_cos',
 'day_sin',
 'day_cos',
 'traffic_score',
 'route_avg_ctat_safe',
 'rating_diff',
 'avg_rating',
 'low_driver_rating',
 'low_customer_rating',
 'driver_score',
 'hourly_demand',
 'route_demand',
 'demand_pressure',
 'route_count',
 'log_price',
 'log_ctat',
 'log_route_count',
 'log_route_price',
 'log_route_ctat',
 'time_distance_interaction',
 'route_complexity',
 'peak_pressure',
 'route_ctat_mean',
 'route_ctat_median',
 'route_ctat_std',
 'route_vtat_mean',
 'route_vtat_median',
 'hour_avg_ctat',
 'hour_avg_vtat',
 'hour_demand',
 'dow_avg_ctat',
 'dow_avg_vtat',
 'distance_bin',
 'dist_bin_ctat',
 'dist_bin_vtat',
 'log_distance_v2',
 'rating_sum',
 'rating_mult',
 'rating_min',
 'rating_max',
 'rating_bucket',
 'rating_bucket_ctat',
 'rating_bucket_vtat',
 'route_hour_key',
 'route_hour_ctat',
 'route_hour_vtat',
 'minute',
 'pickup_key',
 'drop_key',
 'estimated_pickup_time_minute',
 'estimated_drop_time_minute',
 'price_per_km',
 'price_bucket',
 'price_bucket_ctat',
 'price_bucket_vtat']

In [49]:
df['Vehicle Type'].value_counts()

Vehicle Type
Auto             37419
Car              29806
Go Sedan         27141
Motorcycle       22517
Premier Sedan    18111
eBike            10557
Uber XL           4449
Name: count, dtype: int64

In [50]:
object_columns = df.select_dtypes(include='object')
object_columns

,id,Time,user_id,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Payment Method,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides Reason,route_hour_key,pickup_key,drop_key
0,RIDE-000001,00:19:34,CNR4352144,Completed,CID8362794,Motorcycle,Pasar Baru,Cilandak Timur,Cash,No Cancellation,No Cancellation,No Cancellation,No Cancellation,No Cancellation,110_18_0,110_0_19,18_0_19
1,RIDE-000002,01:35:18,CNR9147645,Completed,CID8300238,Car,Kali Anyar,Rawamangun,Uber Wallet,Cancelled,Changed Mind,Cancelled,Traffic Issue,Ride Cancelled Midway,47_147_1,47_1_35,147_1_35
2,RIDE-000003,01:37:50,CNR1009222,Cancelled by Driver,CID2030746,Go Sedan,Serdang,Pengadegan,Debit Card,Cancelled,Driver Taking Too Long,No Cancellation,No Reason Provided,Ride Cancelled Midway,147_125_1,147_1_37,125_1_37
3,RIDE-000004,01:48:03,CNR2740479,Cancelled by Driver,CID3231181,Auto,Tanah Tinggi,Kampung Rawa,Debit Card,No Cancellation,Booked by Mistake,No Cancellation,No Reason Provided,Route Problem,160_61_1,160_1_48,61_1_48
4,RIDE-000005,01:49:56,CNR7650148,Cancelled by Driver,CID3381661,Go Sedan,Jati,Batu Ceper,Debit Card,Cancelled,Booked by Mistake,Cancelled,Vehicle Breakdown,Ride Cancelled Midway,40_2_1,40_1_49,2_1_49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,RIDE-149996,22:58:00,CNR9030698,Completed,CID6939658,Motorcycle,Setu,Kembangan Utara,UPI,No Cancellation,Changed Mind,Cancelled,Traffic Issue,App Error,148_84_22,148_22_58,84_22_58
149996,RIDE-149997,23:03:14,CNR1507833,Completed,CID9905090,eBike,Jatinegara,Grogol Selatan,UPI,No Cancellation,Driver Taking Too Long,Cancelled,Traffic Issue,App Error,41_43_23,41_23_3,43_23_3
149997,RIDE-149998,23:17:05,CNR2265113,Completed,CID4170406,Car,Kebon Melati,Galur,UPI,Cancelled,Changed Mind,Cancelled,Wrong Location,Route Problem,69_36_23,69_23_17,36_23_17
149998,RIDE-149999,23:21:12,CNR4066733,Completed,CID8938559,Uber XL,Utan Panjang,Pinang Ranti,Uber Wallet,No Cancellation,Wrong Pickup Location,Cancelled,Traffic Issue,Ride Cancelled Midway,174_132_23,174_23_21,132_23_21
149999,RIDE-150000,23:36:11,CNR6915581,Incomplete,CID5185745,Auto,Mampang Prapatan,Tegal Parang,UPI,No Cancellation,Found Alternative,No Cancellation,No Reason Provided,Vehicle Breakdown,94_168_23,94_23_36,168_23_36